version: '3.9'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
    volumes:
      - ../..:/workspaces:cached
    #network_mode: service:db
    command: sleep infinity

  novnc:
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11

  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      DISPLAY: novnc:0.0
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
networks:
  x11:

volumes:
  postgres-data:
    driver: local
